rule download_dataset_cats_dogs:
    output:
        directory("data/raw/train"),
        directory("data/raw/test1"),
        "data/raw/sampleSubmission.csv"
    log:
        "workflow/logs/download_dataset.log"
    shell:
        "python src/make_dataset.py cats_and_dogs 2> {log}"

rule download_dataset_denoise:
    output:
        directory("data/raw/denoise")
    log:
        "workflow/logs/download_dataset.log"
    shell:
        "python src/make_dataset.py denoise --path data/raw/denoise 2> {log}"